spring.application.name=cytech_ec

server.servlet.context-path=/cytech_ec
server.port=7777
spring.thymeleaf.cache=false

# ===============================
# MySQL 接続設定（MAMP）
# ===============================
spring.datasource.url=jdbc:mysql://localhost:8889/cytech_ec?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA 設定
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

